version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    hostname: mysql 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ~/Desktop/SQL/dados_bin:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    depends_on:
      - db

# docker-compose up -d